//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParkingBot.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking 🤖.
        /// </summary>
        internal static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Parking.
        /// </summary>
        internal static string auto_parking {
            get {
                return ResourceManager.GetString("auto_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability:.
        /// </summary>
        internal static string availability_ {
            get {
                return ResourceManager.GetString("availability_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available.
        /// </summary>
        internal static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Devices.
        /// </summary>
        internal static string dev_list {
            get {
                return ResourceManager.GetString("dev_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends at.
        /// </summary>
        internal static string ends_at {
            get {
                return ResourceManager.GetString("ends_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Permissions.
        /// </summary>
        internal static string insuf_perm {
            get {
                return ResourceManager.GetString("insuf_perm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string internal_error {
            get {
                return ResourceManager.GetString("internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk Parking.
        /// </summary>
        internal static string kiosk_parking {
            get {
                return ResourceManager.GetString("kiosk_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        internal static string license_plate {
            get {
                return ResourceManager.GetString("license_plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage BT Devices.
        /// </summary>
        internal static string manage_dev {
            get {
                return ResourceManager.GetString("manage_dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove registered devices. To register a device it has to be paired to this device..
        /// </summary>
        internal static string manage_device_text {
            get {
                return ResourceManager.GetString("manage_device_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active parking.
        /// </summary>
        internal static string no_active_parking {
            get {
                return ResourceManager.GetString("no_active_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No relevant parking zones nearby..
        /// </summary>
        internal static string no_region {
            get {
                return ResourceManager.GetString("no_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking not available.
        /// </summary>
        internal static string not_available {
            get {
                return ResourceManager.GetString("not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not supported.
        /// </summary>
        internal static string not_supported_msg {
            get {
                return ResourceManager.GetString("not_supported_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired Devices.
        /// </summary>
        internal static string pair_dev_list {
            get {
                return ResourceManager.GetString("pair_dev_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking started. Ends at.
        /// </summary>
        internal static string parking_started_ends_at {
            get {
                return ResourceManager.GetString("parking_started_ends_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission requirements not met..
        /// </summary>
        internal static string perm_not_met {
            get {
                return ResourceManager.GetString("perm_not_met", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission error.
        /// </summary>
        internal static string permission_error_msg {
            get {
                return ResourceManager.GetString("permission_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number format..
        /// </summary>
        internal static string phone_format_error {
            get {
                return ResourceManager.GetString("phone_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0701234567.
        /// </summary>
        internal static string phone_hint {
            get {
                return ResourceManager.GetString("phone_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration plate..
        /// </summary>
        internal static string plate_format_error {
            get {
                return ResourceManager.GetString("plate_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Devices.
        /// </summary>
        internal static string reg_dev_list {
            get {
                return ResourceManager.GetString("reg_dev_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        internal static string reminder {
            get {
                return ResourceManager.GetString("reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in settings..
        /// </summary>
        internal static string settings_error {
            get {
                return ResourceManager.GetString("settings_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Number.
        /// </summary>
        internal static string sms_num {
            get {
                return ResourceManager.GetString("sms_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS parking started in.
        /// </summary>
        internal static string sms_parking_started_in {
            get {
                return ResourceManager.GetString("sms_parking_started_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to have an account with Parkering Göteborg..
        /// </summary>
        internal static string sms_prereq {
            get {
                return ResourceManager.GetString("sms_prereq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spaces.
        /// </summary>
        internal static string spaces {
            get {
                return ResourceManager.GetString("spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string status_ {
            get {
                return ResourceManager.GetString("status_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or paste your key here.
        /// </summary>
        internal static string token_placeholder {
            get {
                return ResourceManager.GetString("token_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string vehicle {
            get {
                return ResourceManager.GetString("vehicle", resourceCulture);
            }
        }
    }
}
